name: Automatic validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js environment
      uses: textbook/take-action@nodejs
      with:
        node-version: 20
    - name: Install browsers
      run: npx playwright install --with-deps
    - name: Check code styling
      run: npm run lint
    - name: Run unit tests
      run: npm run test:cover
    - name: Run end-to-end 
      id: e2e-test
      run: npm run e2e
    - name: Upload site artifacts
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: dist/
    - name: Upload E2E artifacts
      uses: actions/upload-artifact@v4
      if: failure() && steps.e2e-test.outcome == 'failure'
      with:
        if-no-files-found: error
        name: playwright-report
        path: playwright-report/
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - name: Set up Node.js environment
      uses: textbook/take-action@nodejs
      with:
        install: false
        node-version: 20
    - name: Upload site artifacts
      uses: actions/download-artifact@v4
      with:
        name: website
        path: dist/
    - name: Deploy to GitHub Pages branch
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages --dist dist --user 'github-actions-bot <support+actions@github.com>'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
